// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrr4QKOcF3rDlqDNUAHv3SdRERhJGD4ZU',
    appId: '1:700276656646:web:2e13b32567a48af5199187',
    messagingSenderId: '700276656646',
    projectId: 'hilma-1f152',
    authDomain: 'hilma-1f152.firebaseapp.com',
    storageBucket: 'hilma-1f152.firebasestorage.app',
    measurementId: 'G-ZGS8Q9X9SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRjyAHk0I4UCITmQ0F-gP9-uNsfmNhU4U',
    appId: '1:700276656646:android:55d35325ea74058e199187',
    messagingSenderId: '700276656646',
    projectId: 'hilma-1f152',
    storageBucket: 'hilma-1f152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFbBKpZoixeOL9Qi67e9rLw3oZ6BR0zBc',
    appId: '1:700276656646:ios:ccc8dee17f2852f2199187',
    messagingSenderId: '700276656646',
    projectId: 'hilma-1f152',
    storageBucket: 'hilma-1f152.firebasestorage.app',
    iosBundleId: 'com.example.hilmaUprak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFbBKpZoixeOL9Qi67e9rLw3oZ6BR0zBc',
    appId: '1:700276656646:ios:ccc8dee17f2852f2199187',
    messagingSenderId: '700276656646',
    projectId: 'hilma-1f152',
    storageBucket: 'hilma-1f152.firebasestorage.app',
    iosBundleId: 'com.example.hilmaUprak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrr4QKOcF3rDlqDNUAHv3SdRERhJGD4ZU',
    appId: '1:700276656646:web:19c6abaf63996bc5199187',
    messagingSenderId: '700276656646',
    projectId: 'hilma-1f152',
    authDomain: 'hilma-1f152.firebaseapp.com',
    storageBucket: 'hilma-1f152.firebasestorage.app',
    measurementId: 'G-T8GRNPJTP2',
  );
}
